### ISSUE TITLE
BUG: issue for translate to spanish 

### ISSUE THREAD

**Issue by johnfelipe** [giovanni-bertoncelli/json-translator#1]
source json files here:

https://github.com/KnowageLabs/Knowage-Server/tree/master/knowage-vue/src/i18n/en_US/messages.json

pls help me to solve this
```
✔ Initialized!
⠧ Translating value #2/2159...Not Found: Unable to automatically detect the source language, confidence too low
    at RequestWrapper.formatError (/root/json-translator/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:290:21)
    at /root/json-translator/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:275:45
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TranslatorInCloud.translate (/root/json-translator/node_modules/@giovanni-bertoncelli/json-translator/utils/cloud.js:30:26)
    at async /root/json-translator/node_modules/@giovanni-bertoncelli/json-translator/index.js:30:26
    at async forInNestedRec (/root/json-translator/node_modules/@giovanni-bertoncelli/json-translator/utils/trees.js:21:9)
    at async forInNestedRec (/root/json-translator/node_modules/@giovanni-bertoncelli/json-translator/utils/trees.js:17:7)
    at async JsonTranslator.run (/root/json-translator/node_modules/@giovanni-bertoncelli/json-translator/index.js:23:5)
    at async main (/root/json-translator/node_modules/@giovanni-bertoncelli/json-translator/cli.js:31:3) {
  statusText: 'Not Found',
  status: 404,
  code: 404,
  body: '{"code":404,"error":"Unable to automatically detect the source language, confidence too low"}',
  headers: {
    'content-length': '104',
    'content-type': 'application/json; charset=UTF-8',
    'x-xss-protection': '1; mode=block',
    'x-content-type-options': 'nosniff',
    'content-security-policy': "default-src 'none'",
    'cache-control': 'no-cache, no-store',
    pragma: 'no-cache',
    'content-language': 'en-US',
    'strict-transport-security': 'max-age=31536000; includeSubDomains;',
    'x-dp-watson-tran-id': 'c80cc328-a8f2-4a74-bfd0-390677f0b2ef',
    'x-request-id': 'c80cc328-a8f2-4a74-bfd0-390677f0b2ef',
    'x-global-transaction-id': 'c80cc328-a8f2-4a74-bfd0-390677f0b2ef',
    server: 'watson-gateway',
    'x-edgeconnect-midmile-rtt': '16',
    'x-edgeconnect-origin-mex-latency': '98',
    date: 'Sun, 19 Jun 2022 03:41:58 GMT',
    connection: 'close'
  }
}

```

**Comment by johnfelipe** [comment]
npx json-translator messages.json --from en --to es

**Comment by HighSoftWare96** [comment]
How where you able to resolve this?

**Comment by johnfelipe** [comment]
> npx json-translator messages.json --from en --to es

with this command dear
